backend:
  name: git-gateway # Usado para autenticação com Netlify/GitHub
  branch: main # O branch principal do seu repositório

site_url: https://trocotv.shop # O URL do seu site

media_folder: "images/uploads" # Pasta para guardar imagens
public_folder: "/images/uploads" # Caminho público para as imagens

# Define as coleções de conteúdo editáveis
collections:
  - name: "configuracoes"
    label: "Configurações do Site"
    description: "Edite aqui todos os textos, preços e links do site da Troço TV."
    files:
      - name: "geral"
        label: "Opções Gerais e Textos"
        file: "_data/settings.json" # O painel irá editar este ficheiro
        fields:
          - { label: "Título Principal", name: "hero_title", widget: "string" }
          - { label: "Slogan abaixo do Título", name: "hero_tagline", widget: "string" }
          - { label: "Texto de Introdução", name: "intro_text", widget: "text" }
          - label: "Rodapé"
            name: "footer"
            widget: "object"
            fields:
              - { label: "Texto do Logótipo", name: "logo_text", widget: "string" }
              - { label: "Texto de Copyright", name: "copyright_text", widget: "string" }
          - label: "Visibilidade das Secções"
            name: "visibility"
            widget: "object"
            fields:
              - { label: "Mostrar Secção de Revenda?", name: "reseller_section", widget: "boolean", default: true }
              - { label: "Mostrar Secção 'Como Funciona'?", name: "how_it_works_section", widget: "boolean", default: true }
              - { label: "Mostrar Secção 'Experimente Grátis'?", name: "free_trial_section", widget: "boolean", default: true }
          - label: "Cores do Site"
            name: "cores"
            widget: "object"
            fields:
              - { label: "Cor Principal (Azul)", name: "primaria", widget: "color" }
              - { label: "Cor Principal Escura (para hover)", name: "primaria_escura", widget: "color" }
              - { label: "Cor Secundária (Fundo)", name: "secundaria", widget: "color" }
          - label: "Links Gerais"
            name: "links"
            widget: "object"
            fields:
              - { label: "Link de Contacto WhatsApp", name: "whatsapp", widget: "string" }
              - { label: "Número de Telefone (para texto)", name: "whatsapp_number", widget: "string" }
              - { label: "Link de Suporte Telegram", name: "telegram", widget: "string" }
          - label: "Horário de Atendimento"
            name: "horario_atendimento"
            widget: "list"
            fields:
              - { label: "Título (ex: Segunda a Sexta)", name: "titulo", widget: "string" }
              - { label: "Ícone do Título (ex: fas fa-calendar-day)", name: "icone", widget: "string" }
              - label: "Horários"
                name: "horarios"
                widget: "list"
                fields: 
                  - { label: "Horário (ex: 09h às 22h)", name: "horario", widget: "string" }
          - label: "Redes Sociais"
            name: "redes_sociais"
            widget: "list"
            fields:
              - { label: "Nome da Rede", name: "nome", widget: "string" }
              - { label: "Link Completo (URL)", name: "url", widget: "string" }
              - { label: "Ícone (ex: fab fa-telegram)", name: "icone", widget: "string" }
          - label: "Secção 'Como Funciona'"
            name: "how_it_works_steps"
            widget: "list"
            summary: "{{fields.text}}"
            fields:
              - { label: "Texto do Passo", name: "text", widget: "string" }
          - label: "Secção 'Experimente Grátis'"
            name: "free_trial"
            widget: "object"
            fields:
              - { label: "Título", name: "title", widget: "string" }
              - { label: "Texto Descritivo", name: "text", widget: "string" }
          - label: "Planos para Cliente Final"
            name: "planos_pessoais"
            widget: "list"
            summary: "{{fields.nome}} - R$ {{fields.preco}}"
            fields:
              - { label: "Nome", name: "nome", widget: "string" }
              - { label: "Preço", name: "preco", widget: "number" }
              - { label: "Duração", name: "duracao", widget: "string" }
              - { label: "Popular?", name: "popular", widget: "boolean", default: false }
          - label: "Planos de Revenda (Créditos)"
            name: "planos_revenda"
            widget: "list"
            summary: "{{fields.nome}} - R$ {{fields.preco}}"
            fields:
              - { label: "Nome", name: "nome", widget: "string" }
              - { label: "Preço", name: "preco", widget: "number" }
              - { label: "Benefícios (separados por ';')", name: "beneficios", widget: "string" }