backend:
  name: git-gateway
  branch: main

site_url: https://trocotv.shop # URL do seu site

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "configuracoes"
    label: "Configurações do Site Troço TV"
    description: "Edite aqui todos os textos, preços e links do site."
    files:
      - name: "geral"
        label: "Conteúdo Principal"
        file: "_data/settings.json"
        fields:
          - { label: "Título Principal", name: "hero_title", widget: "string" }
          - { label: "Slogan (texto abaixo do título)", name: "hero_tagline", widget: "string" }
          - label: "Links"
            name: "links"
            widget: "object"
            fields:
              - { label: "Link do WhatsApp para Contato", name: "whatsapp", widget: "string" }
          - label: "Rodapé"
            name: "footer"
            widget: "object"
            fields:
              - { label: "Texto do Logo no Rodapé", name: "logo_text", widget: "string" }
              - { label: "Texto de Copyright", name: "copyright_text", widget: "string" }
          - label: "Redes Sociais"
            name: "redes_sociais"
            widget: "list"
            fields:
              - { label: "Nome da Rede (ex: Instagram)", name: "nome", widget: "string" }
              - { label: "Link Completo (URL)", name: "url", widget: "string" }
              - { label: "Ícone (ex: fab fa-telegram)", name: "icone", widget: "string" }
          - label: "Passos 'Como Funciona'"
            name: "how_it_works_steps"
            widget: "list"
            fields:
              - { label: "Texto do Passo", name: "text", widget: "string" }
          - label: "Planos para Assinantes"
            name: "planos_pessoais"
            widget: "list"
            summary: "{{fields.nome}} - R$ {{fields.preco}}"
            fields:
              - { label: "Nome do Plano", name: "nome", widget: "string" }
              - { label: "Preço (use ponto para decimais, ex: 29.90)", name: "preco", widget: "number", value_type: "float" }
              - { label: "Duração (ex: Acesso por 30 dias)", name: "duracao", widget: "string" }
              - { label: "É o mais popular?", name: "popular", widget: "boolean", default: false }
          - label: "Planos de Revenda (por Créditos)"
            name: "planos_revenda"
            widget: "list"
            summary: "{{fields.nome}} - R$ {{fields.preco}}"
            fields:
              - { label: "Nome do Pacote (ex: 10 Créditos)", name: "nome", widget: "string" }
              - { label: "Preço do Pacote", name: "preco", widget: "number", value_type: "float" }
              - { label: "Benefícios (separados por ';')", name: "beneficios", widget: "string" }